feat: add slim comment step (#108)
Sometimes "post comment" fails because resulting report is too big:

```
Error: Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"} - https://docs.github.com/rest/issues/comments#create-an-issue-comment
```

This patch tries to solve it